name: "Main Pipeline"

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"

      - name: Install Dependencies
        run: bundle install

      - name: Lint and Style Check
        run: bundle exec rubocop

      - name: Scan for Vulnerabilities
        run: gem install bundler-audit && bundler-audit update && bundler-audit check

      - name: Run Unit Tests
        run: bundle exec rspec

      - name: Build Image
        run: |
          docker build \
            -t ${{ env.DOCKER_USERNAME }}/ruby-app:latest \
            -t ${{ env.DOCKER_USERNAME }}/ruby-app:${{ github.ref_name }} \
            -t ${{ env.DOCKER_USERNAME }}/ruby-app:${{ github.ref_name }}-$(git rev-parse --short HEAD) \
            .

      - name: Push Docker Image
        run: |
          echo ${{ env.DOCKER_PASSWORD }} | docker login -u ${{ env.DOCKER_USERNAME }} --password-stdin
          docker push ${{ env.DOCKER_USERNAME }}/ruby-app:latest
          docker push ${{ env.DOCKER_USERNAME }}/ruby-app:${{ github.ref_name }}
          docker push ${{ env.DOCKER_USERNAME }}/ruby-app:${{ github.ref_name }}-$(git rev-parse --short HEAD)
